# TO DO LIST

- make neural network for DQN etc...
- Make super each junction


# Packages

In [48]:
from collections import deque
import numpy as np

In [17]:
from Vissim_env_class import environment, Load_Vissim
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# DQN

In [ ]:
# MAKE IN A LOOP FOR CROSS VALIDATION

class NNet(nn.Module):
    '''
    Neural Network of RL
        # inputs
            - state_size - number of states (int)
            - action_size - number of actions (int)
            - layers - array with number of neurons per layer
    '''
    def __init__(self,state_size,action_size,layers,activation):
        super(NNet,self).__init__()
        
        layers.append(action_size)
        for layer_idx, no_neurons 
        
        

In [197]:
class NNet(nn.Module):
    '''
    Neural Network of RL
        # inputs
            - state_size - number of states (int)
            - action_size - number of actions (int)
            - layers - array with number of neurons per layer
    '''
    def __init__(self,state_size,action_size):
        super(NNet,self).__init__()
    
        self.lay1 = nn.Linear(state_size,48)
        self.lay2 = nn.Linear(48,48)
        self.lay3 = nn.Linear(48,48)
        self.lay4 = nn.Linear(48,action_size)
        
    def forward(self,state):
        x1 = F.relu(self.lay1(state))
        x2 = F.relu(self.lay2(x1))
        x3 = F.relu(self.lay3(x2))
        action_value = self.lay4(x3)
        return action_value

In [129]:
class Replay_Memory(deque):
    def __init__(self,memory_size):
        super(Reply_Memory,self).__init__(maxlen=memory_size)
        
    def sample(self,batch_size=32):
        idx = np.random.randint(len(self), size=batch_size, dtype=int)
        minibatch = np.array([self[i] for i in idx])
        return minibatch

In [240]:
class DQNAgent():
    
    def __init__(self,
                 state_size,
                 action_size,
                 discount_rate,
                 exploration_rate,
                 learning_rate,
                 batch_size,
                 memory_size,
                 copy_weights_frquency,
                 ID = None
                ):
        
        self.net = NNet(state_size,action_size)
        self.target_net = NNet(state_size,action_size)   
        
        self.memory = Replay_Memory(memory_size)
        
        
    def act(self, state):
        '''
        This method chooses an action using an epsilon-greedy method.
            Input : State as an array.
            Output: Action as an integer.
        '''
        if np.random.rand() <= self.epsilon:
            action = random.randrange(self.action_size)
        else:
            act_values = self.values(state)
            action = np.argmax(act_values)
        return action
    
    def train(self,batch_size):
        minibatch = self.memory.sample(batch_size)
    
    
    def copy_weights(self):
        self.target_net.load_state_dict(net.state_dict())
        
    def remember(self, state, action, reward, next_state, done):
        self.memory.append([state, action, reward, next_state, done])
        target = reward \
                + self.gamma \
                    * np.max(self.target_values(next_state))
        
        prediction = values(state)
        
    def target_values(self,state):
        return self.target_net(state).detach().numpy()
    

        
    def values(self,state):
        return self.net(state).detach().numpy()
            
    '''
    The following are methods to match with alvaro's code.
    '''        
    # Command names to match with Alvaro
    def choose_action(self, state):
        return self.act(state)
    
    def learn_batch(self, batch_size, episode):
        pass

## Debug

In [190]:
import gym

In [191]:
env = gym.make('CartPole-v1').unwrapped

In [224]:
state = env.reset()

In [225]:
net = NNet(4,2)

In [226]:
x = torch.Tensor(state)

In [227]:
y=net(x)

In [232]:
z= y.detach().numpy()

In [234]:
z

array([ 0.0897426 , -0.10005645], dtype=float32)

In [235]:
np.argmax(z)

0

In [89]:
memory = Reply_Memory(100)

In [63]:
len(memory)

NameError: name 'self' is not defined

In [91]:
idx =np.random.randint(len(memory), size=32, dtype=int)

In [93]:
idx

array([51, 13, 96, 19, 69, 72, 37, 48, 59, 24, 85, 45, 68, 93, 20, 94, 60,
       58, 59, 76, 32, 57, 59, 29, 38, 20, 45,  5, 89,  0, 83, 64])

In [92]:
[memory[i] for i in idx]

[151,
 113,
 196,
 119,
 169,
 172,
 137,
 148,
 159,
 124,
 185,
 145,
 168,
 193,
 120,
 194,
 160,
 158,
 159,
 176,
 132,
 157,
 159,
 129,
 138,
 120,
 145,
 105,
 189,
 100,
 183,
 164]

In [69]:
memory[idx]

TypeError: only integer scalar arrays can be converted to a scalar index

In [90]:
for i in range(100,200):
    memory.append(i)

In [61]:
memory.sample()

TypeError: only integer scalar arrays can be converted to a scalar index

In [14]:
net = NNet(4,2)
loss = nn.MSELoss()
optimizer = optim.Adam(net.parameters(), lr=0.001)

# Start

In [2]:
from Vissim_env_class import environment, Load_Vissim

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [102]:
class model(nn.Module):
    
    def __init__(self,state_sise, action_st)
    layer_1 = nn.
    

SyntaxError: invalid syntax (<ipython-input-102-0d1efbb44a6d>, line 3)

In [131]:
class Model(nn.Module):

    def __init__(self):
        super(Model, self).__init__()

        # Inputs = 5, Outputs = 3, Hidden = 30
        self.layer1 = nn.Linear(3, 2)
        self.layer2 = nn.Linear(2, 1)

    def forward(self, state):
        x = F.relu(self.layer1(state))
        outputs = self.layer2(x)
        return outputs    

In [132]:
F.mse_loss

<function torch.nn.functional.mse_loss(input, target, size_average=None, reduce=None, reduction='mean')>

In [133]:
model = Model()
model2 = Model()

In [183]:
print(model)

Model(
  (layer1): Linear(in_features=3, out_features=2, bias=True)
  (layer2): Linear(in_features=2, out_features=1, bias=True)
)


In [134]:
input1 = torch.randn(3)
out1 = model(input1)

In [135]:
input2 = torch.randn(3)
out2= model(input2)

In [136]:
loss = F.mse_loss(out1, out2)

In [137]:
loss.backward()

In [154]:
type(torch.rand(3))

torch.Tensor

In [213]:
x = np.array([1.,2.,3.])

In [214]:
y= torch.Tensor(x)

In [220]:
y.max()

tensor(3.)

In [188]:
model([y])

AttributeError: 'list' object has no attribute 'dim'

In [175]:
array = np.arange(1,4)
tensor = torch.from_numpy(array)

In [176]:
tensor

tensor([1, 2, 3], dtype=torch.int32)

In [182]:
y = torch.Tensor(tensor)

TypeError: expected torch.FloatTensor (got torch.IntTensor)

In [177]:
model(tensor)

RuntimeError: Expected object of scalar type Int but got scalar type Float for argument #2 'mat2'

In [118]:
params = list(model.parameters())

In [119]:
params

[Parameter containing:
 tensor([[-0.2663, -0.5589, -0.5606],
         [-0.1385, -0.2442,  0.4444]], requires_grad=True),
 Parameter containing:
 tensor([-0.1851, -0.2033], requires_grad=True),
 Parameter containing:
 tensor([[-0.2431,  0.6619]], requires_grad=True),
 Parameter containing:
 tensor([-0.2123], requires_grad=True)]

In [122]:
params2 = list(model2.parameters())

In [123]:
params2

[Parameter containing:
 tensor([[-0.3254, -0.0731,  0.1346],
         [ 0.5285, -0.1717, -0.5763]], requires_grad=True),
 Parameter containing:
 tensor([ 0.3276, -0.4956], requires_grad=True),
 Parameter containing:
 tensor([[ 0.6751, -0.1357]], requires_grad=True),
 Parameter containing:
 tensor([-0.6297], requires_grad=True)]

In [124]:
model2.load_state_dict(model.state_dict())

In [125]:
params2 = list(model2.parameters())

In [126]:
params2

[Parameter containing:
 tensor([[-0.2663, -0.5589, -0.5606],
         [-0.1385, -0.2442,  0.4444]], requires_grad=True),
 Parameter containing:
 tensor([-0.1851, -0.2033], requires_grad=True),
 Parameter containing:
 tensor([[-0.2431,  0.6619]], requires_grad=True),
 Parameter containing:
 tensor([-0.2123], requires_grad=True)]

In [32]:
from torch import FloatTensor
from torch.autograd import Variable


# Define the leaf nodes
a = Variable(FloatTensor([4]))

weights = [Variable(FloatTensor([i]), requires_grad=True) for i in (2, 5, 9, 7)]

# unpack the weights for nicer assignment
w1, w2, w3, w4 = weights

b = w1 * a
c = w2 * a
d = w3 * b + w4 * c
L = (10 - d)

L.backward()

for index, weight in enumerate(weights, start=1):
    gradient, *_ = weight.grad.data
    print(f"Gradient of w{index} w.r.t to L: {gradient}")

Gradient of w1 w.r.t to L: -36.0
Gradient of w2 w.r.t to L: -28.0
Gradient of w3 w.r.t to L: -8.0
Gradient of w4 w.r.t to L: -20.0


In [34]:
L.backward()
L.grad

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.